/** @format */

import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const outfit = localFont({
  src: './fonts/outfitVF.ttf',
  variable: '--font-outfit',
  weight: '100 200 300 400 500 600 700 800 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${outfit.variable} h-full antialiased`}>
      <body className='min-h-full flex flex-col'>{children}</body>
    </html>
  );
}
